CREATE SCHEMA apl_lancamentos;

CREATE TABLE apl_lancamentos.tab_lancamento (
	id                          serial4                         NOT NULL,
	tipo                        char(1)                         NOT NULL,
	nr_documento                varchar(25)                     NOT NULL,
    descricao                   varchar(150)                    NOT NULL,
	cpt_dh_lancto               timestamp                       NOT NULL,
    cpt_dia                     date                            NOT NULL,
	cpt_ano                     int4                            NOT NULL,
	cpt_mes                     int4                            NOT NULL,
	cpt_per_lancto              int4                            NOT NULL,
	cpt_per_competencia         int4                            NOT NULL,
	part_cadastro_id            int4                                NULL,
	part_empresa_id             int4                            NOT NULL,
	part_organizacao_id         int4                            NOT NULL,
	part_usuario_id             int4                            NOT NULL,
	conta_banco_id              int4                            NOT NULL,
	meio_pagto                  char(1)                         NOT NULL,
	vl_saldo_anterior           numeric(10,2)                   NOT NULL,
	vl_informado                numeric(9,2)                    NOT NULL,
	vl_operacional              numeric(9,2)                    NOT NULL,
	vl_real                     numeric(9,2)                    NOT NULL,
	observacao                  varchar(200)                        NULL,
	contrato_id                 int4                                NULL,
    contrato_tipo               char(1)                             NULL,

	CONSTRAINT pk_lancamentos_lancamento                        PRIMARY KEY (id),
	CONSTRAINT fk_lancamentos_lancamento_organizacao            FOREIGN KEY (part_organizacao_id)        REFERENCES apl_acessos.tab_organizacao(id),
    CONSTRAINT fk_lancamentos_lancamento_empresa                FOREIGN KEY (part_empresa_id)            REFERENCES apl_acessos.tab_empresa(id),
    CONSTRAINT fk_lancamentos_lancamento_usuario                FOREIGN KEY (part_usuario_id)            REFERENCES apl_acessos.tab_usuario(id),
    CONSTRAINT fk_lancamentos_lancamento_cadastro               FOREIGN KEY (part_cadastro_id)           REFERENCES apl_cadastros.tab_cadastro(id),
    CONSTRAINT fk_lancamentos_lancamento_conta_banco            FOREIGN KEY (conta_banco_id)             REFERENCES apl_acessos.tab_empresa_conta(id),
    CONSTRAINT ck_lancamentos_lancamento_contrato_tipo          CHECK (contrato_tipo                     in ('C','V','L','S')),
    CONSTRAINT ck_lancamentos_lancamento_meio_pagamento_tipo    CHECK (meio_pagto                        in ('A','B','C','D','X','Y','Z')),
    CONSTRAINT ck_lancamentos_lancamento_tipo                   CHECK (tipo                              in ('R','D'))
);

CREATE TABLE apl_lancamentos.tab_parcelamento (
	id                          serial4                         NOT NULL,
	nr_documento                varchar(25)                         NULL,
    descricao                   varchar(150)                        NULL,
    is_fatura                   bool                            NOT NULL,
    is_quitada                  bool                            NOT NULL,
    cpt_dh_lancto               timestamp                       NOT NULL,
    cpt_dia                     date                            NOT NULL,
	cpt_ano                     int4                            NOT NULL,
	cpt_mes                     int4                            NOT NULL,
    cpt_per_lancto              int4                            NOT NULL,
	cpt_per_competencia         int4                            NOT NULL,
	part_cadastro_id            int4                            NOT NULL,
    part_empresa_id             int4                            NOT NULL,
    part_organizacao_id         int4                            NOT NULL,
    part_usuario_id             int4                            NOT NULL,
	conta_banco_id              int4                            NOT NULL,
    tipo                        char(1)                         NOT NULL,
    meio_pagto                  char(1)                         NOT NULL,
    parc_neg_num_parcela        int4                            NOT NULL,
	parc_neg_dt_vencto          date                            NOT NULL,
	parc_neg_vl_original        numeric(9,2)                    NOT NULL,
    parc_neg_vl_multa           numeric(7,2)                    NOT NULL,
    parc_neg_vl_juros           numeric(7,2)                    NOT NULL,
    parc_neg_vl_correcao        numeric(7,2)                    NOT NULL,
    parc_neg_vl_desconto        numeric(7,2)                    NOT NULL,
    parc_neg_vl_amortizado      numeric(7,2)                    NOT NULL,
    parc_neg_vl_atual           numeric(9,2)                    NOT NULL,
    parc_neg_is_atrasada        bool                            NOT NULL,
    parc_neg_dias_atraso        int4                            NOT NULL,
    parc_neg_num_pendentes      int4                            NOT NULL,
    parc_neg_is_negociada       bool                            NOT NULL,
    parc_neg_dt_prox_vencto     date                                NULL,
	observacao                  varchar(150)                        NULL,
	contrato_id                 int4                                NULL,
    contrato_tipo               char(1)                             NULL,


	CONSTRAINT pk_lancamentos_parcelamento                      PRIMARY KEY (id),
    CONSTRAINT fk_lancamentos_parcelamento_organizacao          FOREIGN KEY (part_organizacao_id)        REFERENCES apl_acessos.tab_organizacao(id),
    CONSTRAINT fk_lancamentos_parcelamento_empresa              FOREIGN KEY (part_empresa_id)            REFERENCES apl_acessos.tab_empresa(id),
    CONSTRAINT fk_lancamentos_parcelamento_usuario              FOREIGN KEY (part_usuario_id)            REFERENCES apl_acessos.tab_usuario(id),
    CONSTRAINT fk_lancamentos_parcelamento_cadastro             FOREIGN KEY (part_cadastro_id)           REFERENCES apl_cadastros.tab_cadastro(id),
    CONSTRAINT fk_lancamentos_parcelamento_conta_banco          FOREIGN KEY (conta_banco_id)             REFERENCES apl_acessos.tab_empresa_conta(id),
    CONSTRAINT ck_lancamentos_parcelamento_contrato_tipo        CHECK (contrato_tipo                     in ('C','V','L','S')),
    CONSTRAINT ck_lancamentos_parcelamento_meio_pagamento_tipo  CHECK (meio_pagto                        in ('A','B','C','D','X','Y','Z')),
    CONSTRAINT ck_lancamentos_parcelamento_tipo                 CHECK (tipo                              in ('R','D'))
);

CREATE TABLE apl_lancamentos.tab_parcelamento_parcela (
	id                          serial4                         NOT NULL,
	descricao                   varchar(80)                     NOT NULL,
	parc_neg_dt_vencto          date                            NOT NULL,
    parc_neg_num_parcela        int4                            NOT NULL,
	parc_neg_vl_original        numeric(9,2)                    NOT NULL,
	parc_neg_vl_multa           numeric(7,2)                    NOT NULL,
	parc_neg_vl_juros           numeric(7,2)                    NOT NULL,
	parc_neg_vl_correcao        numeric(7,2)                    NOT NULL,
	parc_neg_vl_desconto        numeric(7,2)                    NOT NULL,
    parc_neg_vl_amortizado      numeric(7,2)                    NOT NULL,
    parc_neg_vl_atual           numeric(9,2)                    NOT NULL,
    parc_neg_is_atrasada        bool                            NOT NULL,
    parc_neg_dias_atraso        int4                            NOT NULL,
	parc_neg_num_pendentes      int4                            NOT NULL,
	parc_neg_is_negociada       bool                            NOT NULL,
    parc_neg_dt_prox_vencto     date                                NULL,
	al_correcao                 numeric(5,2)                    NOT NULL,
    al_juros                    numeric(5,2)                    NOT NULL,
    al_multa                    numeric(5,2)                    NOT NULL,
	quit_is_efetuada            bool                            NOT NULL,
	quit_data                   date                                NULL,
	observacao                  varchar(150)                        NULL,
	parc_lancto_id              int4                                NULL,
	bol_is_solicitado           bool                            NOT NULL,
	bol_status                  char(1)                             NULL,
	bol_nr_autorizacao          varchar(40)                         NULL,
	bol_url_impressao           varchar(100)                        NULL,
    bol_linha_digitavel         varchar(60)                         NULL,
    bol_vl_compensado           numeric(9,2)                        NULL,
    bol_dt_pagamento            date                                NULL,
    bol_dt_compensacao          date                                NULL,
	CONSTRAINT pk_lancamentos_lancto_parcela                    PRIMARY KEY (id),
	CONSTRAINT fk_lancamentos_lancto_parc_lancto                FOREIGN KEY (parc_lancto_id)            REFERENCES apl_lancamentos.tab_parcelamento(id),
	CONSTRAINT ck_lancamentos_lancto_parc_lancto_bol_status     CHECK (bol_status                       in ('S','E','P','R','C'))

);

CREATE TABLE apl_lancamentos.tab_parcelamento_parcela_pagto (
	id                          serial4                         NOT NULL,
	cpt_per_competencia         int4                            NOT NULL,
	dt_pagto                    date                            NOT NULL,
	valor                       numeric(9,2)                    NOT NULL,
	meio_pagto                  char(1)                         NOT NULL,
	parcela_id                  int4                            NOT NULL,
	parcelamento_id             int4                            NOT NULL,
	usuario_id                  int4                            NOT NULL,
	conta_banco_id              int4                            NOT NULL,
	bol_nr_autorizacao          varchar(40)                         NULL,
	bol_vl_original             numeric(9,2)                        NULL,

	CONSTRAINT pk_lancamentos_lancto_parcela_pagto              PRIMARY KEY (id),
	CONSTRAINT fk_lancamentos_lancto_parcela_pagto_parcel       FOREIGN KEY (parcela_id)            REFERENCES apl_lancamentos.tab_parcelamento_parcela(id),
	CONSTRAINT fk_lancamentos_lancto_parcela_pagto_parcelto     FOREIGN KEY (parcelamento_id)       REFERENCES apl_lancamentos.tab_parcelamento(id),
	CONSTRAINT fk_lancamentos_lancto_parcela_pagto_conta_banco  FOREIGN KEY (conta_banco_id)        REFERENCES apl_acessos.tab_empresa_conta(id),
	CONSTRAINT fk_lancamentos_lancto_parcela_pagto_usuario      FOREIGN KEY (usuario_id)            REFERENCES apl_acessos.tab_usuario(id),
	CONSTRAINT ck_lancamentos_parclto_parc_meio_pagamento_tipo  CHECK (meio_pagto                   in ('A','B','C','D','X','Y','Z'))
);